<a href="https://colab.research.google.com/github/Arshya1234/Python-assignment./blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [ ]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int64


2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
import numpy as np
arr = np.array([1.5,2.6,3.7])
if arr.dtype == np.float64:
  print("the data type of 'arr' is float64.")
else:
  print("the data type of'arr'' is not float64.")

the data type of 'arr' is float64.



3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np
arr = np.array([1+2j,2+3j,3+4j],dtype = np.complex128)
print(arr)

[1.+2.j 2.+3.j 3.+4.j]


4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1. 2. 3. 4. 5.]


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np
arr = np.array([1.234,2.345,3.456])
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1.234 2.345 3.456]


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


In [ ]:
import numpy as np
def array_attributes(arr):
  shape = arr.shape
  size = arr.size
  dtype = arr.dtype
  return shape,size,dtype

arr = np.array([[1,2,3],[4,5,6]])
shape,size,dtype = array_attributes(arr)
print("shape:",shape)
print("size:",size)
print("Datatype:",dtype)

shape: (2, 3)
size: 6
Datatype: int64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
import numpy as np
def array_dimension(arr):
  return arr.ndim

arr = np.array([[1,2,3],[5,6,7]])
dimension = array_dimension(arr)
print("Dimensionality",dimension)

Dimensionality 2


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.


In [ ]:
import numpy as np
def item_size_info(arr):
  item_size = arr.itemsize
  total_size = arr.nbytes
  return item_size,total_size

arr = np.array([[1,2,3],[4,5,6]])
item_size, total_size = item_size_info(arr)
print("Item size (bytes):",item_size)
print("total size(bytes):", total_size)

Item size (bytes): 8
total size(bytes): 48


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np
def array_strides(arr):
  return arr.strides

arr = np.array([[1,2,3],[4,5,6]])
strides = array_strides(arr)
print("Strides:",strides)

Strides: (24, 8)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
import numpy as np
def shape_stride_relationship(arr):
  shape = arr.shape
  strides = arr.strides
  return shape, strides

arr = np.array([[1,2,3],[4,5,6]])
shape,strides = shape_stride_relationship(arr)
print("Shape:",shape)
print("size:",size)

Shape: (2, 3)
size: 6


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
import numpy as np
def create_zeros_array(n):
  return np.zeros(n)

n = 5
zeros_arr = create_zeros_array(n)
print(zeros_arr)



[0. 0. 0. 0. 0.]


12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
import numpy as np
def create_ones_matrix(rows, cols):
  return np.ones((rows, cols))

rows = 3
cols = 5
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step

In [ ]:
import numpy as np
def generate_range_array(start, stop, step):
  return np.arange(start, stop, step)

start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)

[1 3 5 7 9]


14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
import numpy as np
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)

start = 0
stop = 100
num = 10
linear_space_array = generate_linear_space(start,stop,num)
print(linear_space_array)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
import numpy as np
def create_identity_matrix(n):
  return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16. Write a function that takes a Python list and converts it into a NumPy array.




In [ ]:
import numpy as np
def list_to_numpy_array(py_list):
  return np.array(py_list)

py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)

[1 2 3 4 5]


17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [ ]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array.view()
view_array[0] = 10
print("original array:",original_array)
print("view_array:",view_array)

original array: [10  2  3  4  5]
view_array: [10  2  3  4  5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [ ]:
import numpy as np
def concatenate_arrays(array1, array2, axis=0):
   return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

concatenated_array = concatenate_arrays(array1, array2, axis=1)
print(concatenated_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [ ]:
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated Array:")
print(concatenated_array)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated Array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
import numpy as np
def stack_arrays_vertically(arrays):
  return np.vstack(arrays)
  array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

stacked_array = stack_arrays_vertically([array1, array2, array3])
print(stacked_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:
import numpy as np

def create_integer_array(start, stop, step=1):
    return np.arange(start, stop + 1, step, dtype=int)
tart = 0
stop = 10
step = 2
integer_array = create_integer_array(start, stop, step)
print(integer_array)

[ 0  2  4  6  8 10]


22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
import numpy as np

def generate_equally_spaced_values():
  return np.linspace(0, 1, 10)

equally_spaced_values = generate_equally_spaced_values()
print(equally_spaced_values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, 5)
logarithmically_spaced_values = generate_logarithmically_spaced_values()
print(logarithmically_spaced_values)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd
random_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

print(df)

   Column1  Column2  Column3
0       45       23       79
1       94       96        6
2       20        8       70
3       20       67       79
4       75       80       28


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import pandas as pd
import numpy as np
def replace_negatives_with_zeros(df, column_name):
   df[column_name] = df[column_name].applymap(lambda x: max(0, x))
   return df

data = {'A': [1, -2, 3, -4, 5],
        'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

Original DataFrame:
   A   B
0  1  10
1 -2 -20
2  3  30
3 -4 -40
4  5  50


26. Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]

print("Third element of the array:", third_element)

Third element of the array: 30


27. Retrieve the element at index (1, 2) from the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element_1_2 = arr_2d[1, 2]
print("Element at index (1, 2):", element_1_2)

Element at index (1, 2): 6


28. Using boolean indexing, extract elements greater than 5 from the given NumPy arrayarr = np.array([3, 8, 2, 10, 5, 7])


In [ ]:
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
elements_greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", elements_greater_than_5)

Elements greater than 5: [ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print("Sliced array:", sliced_array)

Sliced array: [3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print("Sub-array:")
print(sub_array)

Sub-array:
[[2 3]
 [5 6]]


31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array

In [ ]:
import numpy as np
def extract_elements_by_indices(arr_2d, indices):
  return arr_2d[np.arange(len(indices)), indices]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([0, 2, 1])  # Example indices

extracted_elements = extract_elements_by_indices(arr_2d, indices)
print("Extracted elements:", extracted_elements)

Extracted elements: [1 6 8]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
import numpy as np
def filter_elements_greater_than_threshold(arr, threshold):
   return arr[arr > threshold]

arr = np.array([1, 5, 10, 15, 20])
threshold = 10

filtered_array = filter_elements_greater_than_threshold(arr, threshold)
print("Filtered array:", filtered_array)

Filtered array: [15 20]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [ ]:
import numpy as np
def extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3):
  return arr_3d[indices_dim1, indices_dim2, indices_dim3]

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])
indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([1, 0])
indices_dim3 = np.array([2, 1])
extracted_elements = extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:", extracted_elements)

Extracted elements: [6 8]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing

In [ ]:
import numpy as np
def filter_elements_with_conditions(arr, condition1, condition2):
    return arr[(condition1) & (condition2)]

arr = np.array([1, 5, 10, 15, 20])
condition1 = arr > 5
condition2 = arr < 15
filtered_array = filter_elements_with_conditions(arr, condition1, condition2)
print("Filtered array:", filtered_array)

Filtered array: [10]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.


In [ ]:
import numpy as np
def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
   return arr_2d[row_indices, col_indices]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([0, 1, 2])
extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)
print("Extracted elements:", extracted_elements)

Extracted elements: [1 5 9]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
import numpy as np
rr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result = arr + 5

print("Result after adding 5 to each element:")
print(result)

Result after adding 5 to each element:
[ 6 10 15 20 25]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting

In [ ]:
import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

arr1_broadcastable = arr1.T

result = arr1_broadcastable * arr2

print("Result after multiplying each row of arr2 by the corresponding element in arr1:")
print(result)

Result after multiplying each row of arr2 by the corresponding element in arr1:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
arr1_broadcastable = arr1.T
result = arr1_broadcastable + arr2

print("Result after adding arr1 to each row of arr2:")
print(result)


Result after adding arr1 to each row of arr2:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [ ]:
import numpy as np
arr1 = np.array([[1],
                 [2],
                 [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print("Result after adding arr1 and arr2 using broadcasting:")
print(result)

Result after adding arr1 and arr2 using broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility

In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10]])
arr2_reshaped = arr2[:, :, np.newaxis]
result = arr1 * arr2_reshaped
print("Result after multiplying arr1 and arr2 using broadcasting:")
print(result)


Result after multiplying arr1 and arr2 using broadcasting:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])




In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print("Column-wise mean:")
print(column_means)

Column-wise mean:
[2.5 3.5 4.5]


42. Find maximum value in each row of the given array:arr = np.array([[1, 2, 3], [4, 5, 6]])


In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_values_in_rows = np.max(arr, axis=1)
print("Maximum values in each row:", max_values_in_rows)


Maximum values in each row: [3 6]


43. For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices_in_columns = np.argmax(arr, axis=0)
print("Indices of maximum value in each column:", max_indices_in_columns)

Indices of maximum value in each column: [1 1 1]


44. For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])


In [4]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr, window_size):
    cumsum = np.cumsum(arr, axis=1)
    return cumsum[:, window_size - 1:] - np.concatenate([np.zeros((arr.shape[0], 1)), cumsum[:, :-window_size]], axis=1)

window_size = 2
moving_sum_result = moving_sum(arr, window_size)
print("Moving sum along rows with window size", window_size, ":\n", moving_sum_result)


Moving sum along rows with window size 2 :
 [[ 3.  5.]
 [ 9. 11.]]


45. In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])

In [5]:
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print("Check if all elements in each column are even:", all_even_columns)

Check if all elements in each column are even: [False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.original_array = np.array([1, 2, 3, 4, 5, 6])

In [6]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = np.reshape(original_array, (m, n))
print("Reshaped matrix:")
print(reshaped_matrix)

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened arrayinput_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print("Flattened array:")
print(flattened_array)

Flattened array:
[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [9]:
import numpy as np
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along rows:")
print(concatenated_array)


concatenated_array = concatenate_arrays(array1, array2, axis=1)  # Concatenate along columns (axis=1)
print("\nConcatenated array along columns:")
print(concatenated_array)

Concatenated array along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array along columns:
[[1 2 5 6]
 [3 4 7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axisoriginal_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
import numpy as np
def split_array(array, num_splits, axis=0):
    return np.split(array, num_splits, axis=axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arrays = split_array(original_array, num_splits=3, axis=0)  # Split along rows (axis=0)
print("Split arrays along rows:")
for arr in split_arrays:
    print(arr)
split_arrays = split_array(original_array, num_splits=3, axis=1)  # Split along columns (axis=1)
print("\nSplit arrays along columns:")
for arr in split_arrays:
    print(arr)

Split arrays along rows:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split arrays along columns:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [15]:
import numpy as np
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
   for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Result array:", result_array)


Result array: None


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [17]:
import numpy as np
arr1 = np.random.randint(1, 100, size=(5, 5))
print("arr1:")
print(arr1)
arr2 = np.arange(1, 11)
print("\narr2:")
print(arr2)


arr1:
[[37 69 56 47 69]
 [81 98 63 23  8]
 [68 28 88  8 58]
 [72 24  8 30 98]
 [70 14 44 42 62]]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [18]:
import numpy as np
arr1 = np.arange(10, 0, -1)
print("arr1:")
print(arr1)
arr2 = np.arange(1, 11)
print("\narr2:")
print(arr2)
result = arr1 - arr2
print("\nResult of element-wise subtraction:")
print(result)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [25]:
import numpy as np
rr1 = np.random.randint(1, 100, size=(5, 5))
print("arr1:")
print(arr1)
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[1 2 3 4 5]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [26]:
import numpy as np
arr1 = np.arange(2, 12, 2)
print("arr1:")
print(arr1)
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)
result = arr1 / arr2
print("\nResult of element-wise division:")
print(result)

arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [27]:
import numpy as np
arr1 = np.arange(1, 6)
print("arr1:")
print(arr1)
arr2 = np.flip(arr1)
print("\narr2:")
print(arr2)
result = arr1 ** arr2
print("\nExponentiation of arr1 raised to the power of arr2 element-wise:")
print(result)

arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Exponentiation of arr1 raised to the power of arr2 element-wise:
[ 1 16 27 16  5]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [28]:
import numpy as np
arr1 = np.arange(1, 6)
print("arr1:")
print(arr1)
arr2 = arr1[::-1]
print("\narr2:")
print(arr2)
result = arr1 ** arr2
print("\nExponentiation of arr1 raised to the power of arr2 element-wise:")
print(result)

arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Exponentiation of arr1 raised to the power of arr2 element-wise:
[ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [29]:
import numpy as np
def count_substring_occurrences(arr, substring):
    return sum(1 for string in arr if substring in string)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print("Occurrences of '{}' in the array: {}".format(substring, occurrences))

Occurrences of 'hello' in the array: 3


57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [30]:
import numpy as np
def extract_uppercase_chars(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase_chars(arr)
print("Uppercase characters from the array:")
print(uppercase_chars)

Uppercase characters from the array:
['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [31]:
import numpy as np
def replace_substring(arr, old_substring, new_substring):
    return np.array([string.replace(old_substring, new_substring) for string in arr])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'ap'
new_substring = 'xx'
result = replace_substring(arr, old_substring, new_substring)
print("Array after replacing '{}' with '{}' :".format(old_substring, new_substring))
print(result)

Array after replacing 'ap' with 'xx' :
['xxple' 'banana' 'grxxe' 'pinexxple']


In [ ]:
59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [32]:
import numpy as np

def concatenate_arrays_elementwise(arr1, arr2):
    return np.char.add(arr1, arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_array = concatenate_arrays_elementwise(arr1, arr2)
print("Concatenated array element-wise:")
print(concatenated_array)

Concatenated array element-wise:
['HelloOpen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [33]:
import numpy as np
def longest_string_length(arr):
    return np.max(np.vectorize(len)(arr))
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr)
print("Length of the longest string in the array:", longest_length)

Length of the longest string in the array: 9


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [35]:
import numpy as np
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [928 991 934 592 800 116 470 826 655 830 735 814  61   4 709 448 232 165
 491 157 241 514 796 262 505  52  31 558 760 979 894 413 866 370 580 977
 766 717 756 199   4 996 101 465 993 638 316 639 617 183 410 177 666 189
 917 756 637 893 629 910 456 235 246 801 608 231  32 202 276 557 287 910
 741 141 502  70 753  34   4  72 638 988 702 315 325  10 517  84 977 629
 915 632 518 581 313 506 167  25 917 576]
Mean: 508.23
Median: 537.5
Variance: 94392.21710000001
Standard Deviation: 307.2331640627359


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset

In [36]:
import numpy as np
dataset = np.random.randint(1, 101, size=50)
percentile_25th = np.percentile(dataset, 25)
percentile_75th = np.percentile(dataset, 75)
print("Dataset:", dataset)
print("25th Percentile:", percentile_25th)
print("75th Percentile:", percentile_75th)


Dataset: [52 30 38 18 70 43 40 34 43  1 20 20 41 76  5 15 29 47 33 19 13 15 69 85
 31  1 35 74 41 58 94  1 83 29 90 60 36 64 22 79 61 66  5 17 74 61 69 91
 49 93]
25th Percentile: 20.5
75th Percentile: 68.25


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [37]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 6, 8, 10])
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]
print("Correlation coefficient between the two arrays:", correlation_coefficient)

Correlation coefficient between the two arrays: 0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.




In [38]:
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result of matrix multiplication:
[[19 22]
 [43 50]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [39]:
import numpy as np
dataset = np.random.randint(10, 1001, size=50)
percentiles = np.percentile(dataset, [10, 25, 50, 75, 90])
first_quartile = np.percentile(dataset, 25)
third_quartile = np.percentile(dataset, 75)
print("Dataset:", dataset)
print("10th Percentile:", percentiles[0])
print("25th Percentile (First Quartile):", first_quartile)
print("50th Percentile (Median):", percentiles[2])
print("75th Percentile (Third Quartile):", third_quartile)
print("90th Percentile:", percentiles[4])

Dataset: [794 679 943 845 332 575 908 647 831 324 767 303 363 286 996 426 520 893
 646 660  53 939 239 662 168 629 248 643 294 470 697 904 726 569 870 830
 598  72 684 451 510  59 757 376 832 653 400 482 519 205]
10th Percentile: 235.60000000000002
25th Percentile (First Quartile): 366.25
50th Percentile (Median): 613.5
75th Percentile (Third Quartile): 764.5
90th Percentile: 894.1


66. Create a NumPy array of integers and find the index of a specific element.

In [40]:
import numpy as n
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
element_to_find = 5
index = np.where(arr == element_to_find)[0]
element_to_find = 5
index = np.where(arr == element_to_find)[0]

67. Generate a random NumPy array and sort it in ascending order.

In [41]:
import numpy as np
random_array = np.random.randint(1, 100, size=10)
print("Random array:")
print(random_array)

sorted_array = np.sort(random_array)
print("\nSorted array in ascending order:")
print(sorted_array)

Random array:
[35 79 67 42 91 21  4 35 92  5]

Sorted array in ascending order:
[ 4  5 21 35 35 42 67 79 91 92]


68. Filter elements >20  in the given NumPy arrayarr = np.array([12, 25, 6, 42, 8, 30])

In [42]:
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print(filtered_arr)


[25 42 30]


69. Filter elements which are divisible by 3 from a given NumPy array.arr = np.array([1, 5, 8, 12, 15])

In [43]:
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
print(filtered_arr)

[12 15]


70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.arr = np.array([10, 20, 30, 40, 50])


In [44]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print(filtered_arr)

[20 30 40]


71. For the given NumPy array, check its byte order using the `dtype` attribute byteorderarr = np.array([1, 2, 3])


In [45]:
import numpy as np
byteorderarr = np.array([1, 2, 3])
byteorder = byteorderarr.dtype.byteorder
print("Byte Order:", byteorder)

Byte Order: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [46]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print("Byte-swapped array:", arr)

Byte-swapped array: [16777216 33554432 50331648]


73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [47]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

Original array: [1 2 3]
Swapped byte order array: [16777216 33554432 50331648]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [48]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

system_byte_order = np.dtype(np.int32).byteorder

if system_byte_order != '=':
    swapped_arr = arr.newbyteorder(system_byte_order)
else:
    swapped_arr = arr

print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

Original array: [1 2 3]
Swapped byte order array: [1 2 3]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`arr = np.array([1, 2, 3], dtype=np.int32)

In [51]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder

if byte_order != '=':
    print("Byte swapping is necessary for the current system.")
else:
    print("No byte swapping is necessary for the current system.")

No byte swapping is necessary for the current system.


76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [52]:
import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("Original array arr1:", arr1)
print("Modified copy array copy_arr:", copy_arr)

Original array arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array copy_arr: [100   2   3   4   5   6   7   8   9  10]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [53]:
import numpy as np

matrix = np.random.randint(0, 10, size=(3, 3))

view_slice = matrix[:2, :2]

print("Original Matrix:")
print(matrix)
print("\nView Slice:")
print(view_slice)
view_slice[0, 0] = 100
print("\nAfter modifying view_slice:")
print(matrix)

Original Matrix:
[[2 7 4]
 [5 4 7]
 [9 6 3]]

View Slice:
[[2 7]
 [5 4]]

After modifying view_slice:
[[100   7   4]
 [  5   4   7]
 [  9   6   3]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

In [54]:
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
print("Original array array_a:")
print(array_a)
print("\nView Slice view_b:")
print(view_b)
view_b += 5
print("\nAfter broadcasting addition of 5 to view_b:")
print(array_a)

Original array array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View Slice view_b:
[[1 2]
 [4 5]]

After broadcasting addition of 5 to view_b:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [55]:
import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.T.reshape(4, 2)

print("Original array orig_array:")
print(orig_array)
print("\nReshaped view reshaped_view:")
print(reshaped_view)

reshaped_view[0, 0] = 100
print("\nAfter modifying reshaped_view:")
print(orig_array)

Original array orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view reshaped_view:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

After modifying reshaped_view:
[[100   2   3   4]
 [  5   6   7   8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [58]:
import numpy as np
data = np.random.randint(0, 10, size=(3, 4))

data_copy = data[data > 5].copy()
print("Original array data:")
print(data)
print("\nCopy of elements greater than 5 data_copy:")
print(data_copy)

data_copy[0] = 100

print("\nAfter modifying data_copy:")
print("Original array data:")
print(data)

Original array data:
[[8 6 7 4]
 [9 5 6 1]
 [4 1 9 5]]

Copy of elements greater than 5 data_copy:
[8 6 7 9 6 9]

After modifying data_copy:
Original array data:
[[8 6 7 4]
 [9 5 6 1]
 [4 1 9 5]]


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [61]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])
addition_result = A + B
subtraction_result = A - B
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result (A + B):")
print(addition_result)
print("\nSubtraction Result (A - B):")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition Result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction Result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [63]:
import numpy as np
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
result = np.dot(C, D)
print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]


83. Create a matrix `E` and find its transpose.

In [64]:
import numpy as np
E = np.array([[1, 2, 3],
              [4, 5, 6]])
transposed_E = np.transpose(E)
print("Matrix E:")
print(E)

Matrix E:
[[1 2 3]
 [4 5 6]]


84. Generate a square matrix `F` and compute its determinant.

In [65]:
import numpy as np
E = np.array([[1, 2, 3],
              [4, 5, 6]])
transposed_E = np.transpose(E)
print("Matrix E:")
print(E)

print("\nTranspose of matrix E:")
print(transposed_E)

Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


85. Create a square matrix `G` and find its inverse.

In [66]:
import numpy as np
G = np.array([[4, 7],
              [2, 6]])
inverse_G = np.linalg.inv(G)
print("Matrix G:")
print(G)

print("\nInverse of matrix G:")
print(inverse_G)

Matrix G:
[[4 7]
 [2 6]]

Inverse of matrix G:
[[ 0.6 -0.7]
 [-0.2  0.4]]
